# Generated by Django 5.2.12 on 2026-04-17 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af5054ab-adcd-477a-9048-7e67ae6bca94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af5054ab-adcd-477a-9048-7e67ae6bca94'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af5054ab-adcd-477a-9048-7e67ae6bca94'), editable=False, primary_key=True, serialize=False),
        ),
    ]
