# Generated by Django 5.2.12 on 2026-04-17 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_id_alter_order_id_alter_orderitem_id'),
        ('users', '0003_alter_customerprofile_id_alter_driverprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='users.customerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
