# Generated by Django 5.2.12 on 2026-04-21 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_customer_alter_cart_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
