# Generated by Django 5.2.12 on 2026-04-21 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cart_id_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
    ]
