# Generated by Django 5.2.12 on 2026-04-21 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cart_id_alter_order_id_alter_orderitem_id'),
        ('users', '0006_alter_customerprofile_id_alter_driverprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_order', to='users.driverprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
    ]
