# Generated by Django 5.2.12 on 2026-04-17 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customerprofile_id_alter_driverprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e485d6e-fa47-42b9-af69-900f7d3d79cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
