# Generated by Django 5.2.12 on 2026-04-21 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerprofile_id_alter_driverprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
    ]
