# Generated by Django 5.2.12 on 2026-04-21 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customerprofile_id_alter_driverprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
    ]
