# Generated by Django 5.2.12 on 2026-04-16 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('f667f173-d9ce-4767-876b-447c99755e59'), editable=False, primary_key=True, serialize=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_reviews', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('preparation_time', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menuitem_images/')),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('side_dish', 'Side Dish')], default='appetizer', max_length=20)),
                ('dietary_info', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('none', 'None')], default='none', max_length=20)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('f667f173-d9ce-4767-876b-447c99755e59'), editable=False, primary_key=True, serialize=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_reviews', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('cuisine_type', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('mexican', 'Mexican'), ('american', 'American'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('mediterranean', 'Mediterranean')], default='indian', max_length=20)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logo_images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurant_banner_images/')),
                ('opening_time', models.TimeField(null=True)),
                ('closing_time', models.TimeField(null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'restaurant_profiles',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('f667f173-d9ce-4767-876b-447c99755e59'), editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
