# Generated by Django 5.2.12 on 2026-04-16 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('restaurants', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menuitem', to='restaurants.restaurantprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_review', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='users.driverprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_reviews', to='restaurants.menuitem'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_review', to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_review', to='restaurants.restaurantprofile'),
        ),
        migrations.AddIndex(
            model_name='restaurantprofile',
            index=models.Index(fields=['-created_at'], name='newest_restaurant_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['-created_at'], name='newest_menuitem_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant'], name='restaurant_menuitem_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='newest_review_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant'], name='restaurant_review_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer'], name='customer_review_idx'),
        ),
    ]
