# Generated by Django 5.2.12 on 2026-04-21 06:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_id_alter_restaurantprofile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='total_reviews',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19e47177-3d2a-4c75-a157-255c08dd82e7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
