# Generated by Django 5.2.12 on 2026-04-21 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_menuitem_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b520239-6b90-449c-916d-796dcaf4e040'), editable=False, primary_key=True, serialize=False),
        ),
    ]
