# Generated by Django 5.2.12 on 2026-04-21 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_menuitem_average_rating_menuitem_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a32e895-f583-4968-b03e-c79a0a7cf968'), editable=False, primary_key=True, serialize=False),
        ),
    ]
