# Generated by Django 5.2.12 on 2026-04-21 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_menuitem_id_alter_restaurantprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d99c2acb-74f9-45a4-aafa-bb125fc61560'), editable=False, primary_key=True, serialize=False),
        ),
    ]
